### ISSUE TITLE
I think we don't have a need to use this package.

### ISSUE THREAD

**Issue by muaadhsherif** [UltCombo/atom-sublime-block-comment#7]
Thanks for who did this package, but I think we don't have a need to use this package as atom does this without packages. Just type:
**ctrl-/**          : to make the hole line as a comment.
**ctrl-shift-/** : to comment the selected text and if there is no-selected text it gives you an empty comment.

**Comment by muaadhsherif** [comment]
I'm very sorry for this post. I'll delete it. I don't know, yesterday ctrl + shift + / was working but now it doesn't. I don't know the reason.
I think Because I uninstalled the package and then ctrl+shift+/ was still working, so I thought It works without the package. Maybe first I had to reopen Atom.
I'm sorry.

**Comment by UltCombo** [comment]
Don't worry, in fact I would very much love to have this functionality built-in into the Atom Editor. I developed this package out of necessity as this functionality was not available in Atom.

To be perfectly honest, I have switched my main editor from Atom to VS Code some months ago and I haven't been paying much attention to my Atom extensions since then. It would be great if Atom had this functionality built-in so that more dedicated maintainers would give it the proper attention.

Let me when/if Atom implements this functionality so that I can mark this package as deprecated. Meanwhile I'll try to refactor the code to make it easier to maintain soon and then look for people interested in maintaining this package.
